DROP TABLE IF EXISTS participant_answer;
DROP TABLE IF EXISTS participant;
DROP TABLE IF EXISTS event_candidate;
DROP TABLE IF EXISTS event;

CREATE TABLE IF NOT EXISTS event (
  event_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(64) NOT NULL,
  description VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS event_candidate (
  candidate_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id int REFERENCES event(event_id),
  candidate VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS participant (
  participant_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  participant_name VARCHAR(64) NOT NULL,
  comment VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS participant_answer (
  candidate_id int REFERENCES event_candidate(candidate_id),
  participant_id int REFERENCES participant(participant_id),
  answer CHAR,
  PRIMARY KEY(candidate_id, participant_id)
);